### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by ccvcd** [ofpay/dubbo-remoting-netty4#1]
可有人说”dubbo中的那些“坑"(3)-netty4-rpc网络接口中的高并发的bug“，不知道你们在使用中是否如他所说呢？

**Comment by wuwen5** [comment]
什么bug呢？可以发下链接么？这个是早前扩展，当时做了下压测没有发现明显优势，但也没有发现什么bug

**Comment by ccvcd** [comment]
http://my.oschina.net/aruan/blog/351622

**Comment by wuwen5** [comment]
@ccvcd 没有这样的问题，不知道他是如何改造的，如果能看到他改造的源码最好。

有点需要注意的 Netty3 中TCP_NODELAY默认值是false，而netty4中默认值是true,
所以保持dubbo netty3同样的实现 这个需要保持一致。Netty4中在server端要设置为false，否则在做压测结果对比的时候会差距很大.
因为这个值netty3和4是反的，如果直接按照dubbo netty3 改造就会出现这样的问题，性能测试的结果相差很大。

我们反复做过压测，遇到过一些问题也经过一些调整，目前的版本性能方面没有上文说的那样，基本和netty3差不多，gc方面比Netty3要好，虽说不差，但是也没有特别明显的优势，所以我们暂时并没有用于生产。

你也可以拿我们这个版本进行下压测对比，有问题欢迎反馈。

**Comment by wuwen5** [comment]
http://my.oschina.net/aruan/blog/351622
这篇文章上提到的

```
而我们InternalDecoder的代码为

      message = com.alibaba.dubbo.remoting.buffer.ChannelBuffers.wrappedBuffer(
                    input.toByteBuffer());
```

不知道他的具体实现，我们这边是用的SimpleChannelInboundHandler，默认是autoRelease.
message = com.alibaba.dubbo.remoting.buffer.ChannelBuffers.wrappedBuffer(
                    input.nioBuffer());
